Fix extract version

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -33,45 +33,30 @@ workflows:
         script: |
           LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --credentials "$SERVICE_ACCOUNT_JSON_KEY")
 
+          LATEST_VERSION_NAME=$(yarn -s cd:extract-version $PACKAGE_NAME $SERVICE_ACCOUNT_JSON_KEY)
+
+          if [ -z "$LATEST_VERSION_NAME" ]; then
+            echo "Failed to extract LATEST_VERSION_NAME"
+            exit 1
+          fi
+
           if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]
            then
-            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-            MAJOR_VERSION=1
-            MINOR_VERSION=0
-            PATCH_VERSION=$UPDATED_BUILD_NUMBER
-          else
-            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-            
-            
-            # Imprimir la salida del comando google-play tracks get para depuración
-            echo "Fetching latest version from production track:"
-            TRACK_OUTPUT=$(google-play tracks get --package-name "$PACKAGE_NAME" --track "production" --credentials "$SERVICE_ACCOUNT_JSON_KEY")
-            echo "$TRACK_OUTPUT"
-            DRAFT_FOUND=0
-
-            # Intentar extraer el nombre de la versión en estado draft
-            while IFS= read -r line; do
-             if echo "$line" | grep -q 'Status: draft'; then
-                DRAFT_FOUND=1
-             elif [ $DRAFT_FOUND -eq 1 ] && echo "$line" | grep -q 'Name:'; then
-                LATEST_VERSION_NAME=$(echo "$line" | awk -F ': ' '{print $2}' | tr -d '", ')
-             break
-            fi
-            done <<< "$TRACK_OUTPUT"
-
-            # Imprimir el valor de LATEST_VERSION_NAME para verificar
-            echo "LATEST_VERSION_NAME extracted: $LATEST_VERSION_NAME"
-            
-            MAJOR_VERSION=$(echo $LATEST_VERSION_NAME | cut -d '.' -f 1)
-            MINOR_VERSION=$(echo $LATEST_VERSION_NAME | cut -d '.' -f 2)
-            PATCH_VERSION=$(echo $LATEST_VERSION_NAME | cut -d '.' -f 3)
-           
-            PATCH_VERSION=$(($PATCH_VERSION + 1))
+            echo "Failed to extract LATEST_GOOGLE_PLAY_BUILD_NUMBER"
+            exit 1
           fi
+
+          UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+
+          echo "LATEST_VERSION_NAME extracted: $LATEST_VERSION_NAME"
+            
+          MAJOR_VERSION=$(echo $LATEST_VERSION_NAME | cut -d '.' -f 1)
+          MINOR_VERSION=$(echo $LATEST_VERSION_NAME | cut -d '.' -f 2)
+          PATCH_VERSION=$(echo $LATEST_VERSION_NAME | cut -d '.' -f 3)
+          PATCH_VERSION=$(($PATCH_VERSION + 1))
 
           NEW_VERSION_NAME=$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
 
-          echo "$NEW_VERSION_NAME"
           sed -i "" "s/versionCode [0-9]*/versionCode $UPDATED_BUILD_NUMBER/" android/app/build.gradle
           sed -i '' "s/versionName \".*\"/versionName \"$NEW_VERSION_NAME\"/" android/app/build.gradle
 
